name = "WhittakerCoulomb"
uuid = "a183c6a1-9880-467b-aa39-ddde75f7ab5d"
version = "0.1.0"
authors = ["banana-bred <j.forer@posteo.net>"]

[deps]
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
HypergeometricFunctions = "0.3.28"
SpecialFunctions = "2.7.1"
