name = "WhittakerCoulomb"
uuid = "a183c6a1-9880-467b-aa39-ddde75f7ab5d"
version = "0.1.0"
authors = ["banana-bred <j.forer@posteo.net>"]

[deps]
CoulombFunctions = "a1073327-32f2-4398-bd61-1b686fd668f2"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
CoulombFunctions = "0.1.0"
DifferentialEquations = "7.17.0"
HypergeometricFunctions = "0.3.28"
Revise = "3.13.2"
SpecialFunctions = "2.7.1"
